# Generated by Django 4.2 on 2023-09-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no1", models.BigIntegerField()),
                ("no2", models.BigIntegerField()),
                ("output_list", models.CharField(max_length=50)),
            ],
        ),
    ]
